<?php
$title = "<title>Daily Water Level-Percentiles by Month - Methods - Everglades Depth Estimation Network (EDEN)</title>\n";
require ($_SERVER['DOCUMENT_ROOT'] . '/../eden/ssi/eden-head.php');
?>
<h3>Daily Water-Level Percentiles by Month &ndash; Methods</h3>
<p>Two approaches are used to compare water levels in the Everglades during the <a href="http://www.evergladesplan.org/pm/program_docs/ertp.aspx">Everglades Restoration Transition Plan (ERTP)</a> period with water levels during the <a href="http://www.saj.usace.army.mil/Portals/44/docs/Planning/EnvironmentalBranch/EnvironmentalDocs/IOP_02_SEIS_37.pdf">Interim Operational Plan (IOP)</a> period. Both approaches plot daily median water levels during the <abbr title="Everglades Restoration Transition Plan">ERTP</abbr> period on plots showing daily water-level percentiles that are computed for each month (values of daily water levels that were not exceeded a given percentage of the time during a given month) using water-level data from the <abbr title="Interim Operational Plan">IOP</abbr> period in Water Conservation Areas (WCA) 3A and 3B and Everglades National Park (<abbr title="Everglades National Park">ENP</abbr>). The first approach generates these plots using daily median water levels from the marsh water-level gages (<a href="#figure1">Fig. 1</a>). The second approach generates these plots using the EDEN daily median water-level estimates at tree islands in the marshes of <abbr title="Water Conservation Area 3 A">WCA3A</abbr>, <abbr title="Water Conservation Area 3 B">WCA3B</abbr>, and the <abbr title="Everglades National Park">ENP</abbr> that are derived from the estimated historical water levels at EDEN cell locations that coincide with the tree islands (<a href="#figure2"><abbr title="figure">Fig.</abbr> 2</a>).</p>
<figure style="width:640px;margin:20px auto;border:1px solid black">
  <a id="figure1"></a><a href="images/NA_Graph_Example_fig1.gif" target="_blank"><img src="images/NA_Graph_Example_fig1th.gif" alt="Example graph for gage 3A9" height="426" width="640"></a>
  <figcaption class="caption" style="background-color:#f1fcdd"><strong>Figure 1 -- </strong>Example daily water-level percentiles by month for a marsh gage. [ <a href="images/NA_Graph_Example_fig1.gif" target="_blank">larger version</a> ]</figcaption>
</figure>
<figure style="width:640px;margin:20px auto;border:1px solid black">
  <a id="figure2"></a><a href="images/NA_Graph_Example_fig2.gif" target="_blank"><img src="images/NA_Graph_Example_fig2th.gif" alt="Example graph for a tree island" height="427" width="640"></a>
  <figcaption class="caption" style="background-color:#f1fcdd"><strong>Figure 2 -- </strong>Example daily water-level percentiles by month for a tree island. [ <a href="images/NA_Graph_Example_fig2.gif" target="_blank">larger version</a> ]</figcaption>
</figure>
<p>The daily water-level percentile for a specified month is defined as the daily water level at a location that has not been exceeded by a specified percentage of the days occurring during that month of the year and over the period of interest. Computations of the daily water-level percentiles for a given month are based on the daily median water-levels at a location (gage or tree island) for all the days of that month during the <abbr title="Interim Operational Plan">IOP</abbr> period. These data are ranked by water level, and then a non-exceedence probability is computed for each daily value using a plotting position formula (Helsel and Hirsch, 1995). The value for specific percentiles (10<sup>th</sup>, 25<sup>th</sup>, 50<sup>th</sup>, 75<sup>th</sup>, and 90<sup>th</sup>) is determined by interpolation between the computed values and then plotted. Colors are used to separate <em>above average</em> (<strong>blue</strong>, greater than 75<sup>th</sup> percentile), <em>average</em> (<strong>green</strong>, between 25<sup>th</sup> and 75<sup>th</sup> percentile), and <em>below average</em> (<strong>brown</strong>, less than 25<sup>th</sup> percentile) conditions.</p>
<p>For example, the percentiles for June during the <abbr title="Interim Operational Plan">IOP</abbr> period are computed by using 300 daily median water-level values that occurred in the month of June during the period July 2002 through October 2012 (10 years times 30 days in June). For gage 3A9, <a href="#figure1">figure 1</a> shows that the daily-median water levels for all of the days in June during the IOP period were less than 7.98 feet 25 percent of the time, and less than 8.99 feet 75 percent of the time. Similarly, 90 percent of all the days in September during the IOP period had a daily mean water level of 10.40 feet <abbr title="North American Vertical Datum of 1988">NAVD88</abbr> or lower. It should be noted that these daily water-level percentiles provide no information about the chronological sequence or monthly distribution of the daily water levels.</p>
<p><em>Helsel, R.M., and Hirsch, D.R., 1995, <a href="http://www.sciencedirect.com/science/bookseries/01661116/49">Studies in environmental science 49</a> - Statistical method in water resources: Amsterdam, Elsevier Science, 529 <abbr title="pages">p.</abbr></em></p>
<h4>Daily Water Level Percentiles by Month - Water Levels at Gages</h4>
<p>The daily water-level percentiles plotted by month for each marsh gage are based on the water-level data measured at that gage during the period. Superimposing a &quot;recent conditions&quot; daily median water-level hydrograph on the plot of the daily water-level percentiles provides a comparison of current water-level conditions during the (ERTP) period with conditions during the (IOP) period.</p>
<p>The maximum and minimum daily water levels for each month during the <abbr title="Interim Operational Plan">IOP</abbr> are also shown on the daily water-level percentiles plot for each gage, and are the highest and lowest, respectively, daily water levels at that gage for that month during the <abbr title="Interim Operational Plan">IOP</abbr> period. The average ground elevation at the gage is plotted, and, during the dry season, water levels at some gages fall below the land surface. The reliability of the data under these dry season conditions varies based on the gage construction and the site conditions that control the hydraulic connection between surface water and groundwater in the vicinity of the gage. Some gages have stilling wells that record water levels up to two or more feet below land surface while other gages may be wells only a fraction of a foot deep. Unfortunately, information does not exist to determine with certainty the accuracy of the data in these circumstances. Therefore any gage data recorded below the land surface is of unknown quality and is considered poor. Several of the water-level gages in the EDEN network are shallow groundwater gages, and the confidence of these data is not reduced to poor when water levels fall below land surface.</p>
<h4>Daily Water Level Percentiles by Month - Water Levels at Tree Islands</h4>
<p>The approach for the tree island is the same that is used for the marsh gages, with the exception that current and previous (i.e. (IOP) water-level values are estimated using the EDEN surface-water model, rather than measurements from a gaging station. The daily water-level percentiles plotted by month for each tree island are based on the EDEN water-level surfaces generated daily by the EDEN surface-water model during the <abbr title="Interim Operational Plan">IOP</abbr> period. The EDEN surface-water model has a root mean square error less than 3.4 centimeters in <abbr title="Water Conservation Area 3 A">WCA3A</abbr> and <abbr title="Water Conservation Area 3 B">WCA3B</abbr> and less than 6.6 centimeters in Everglades National Park (Volin and others, 2008).</p>
<p>Using the daily water-level surface generated by the EDEN surface-water model, the current water level at each tree island is estimated for its cell location. These water levels are plotted on the daily water-level percentile plots after a 4-day delay to allow the data-collection agencies to quality assure the provisional real-time data at gages used for input to the model.</p>
<p>The maximum and minimum water levels for each month during the IOP are identified on the daily water-level percentiles plot for each tree island and are the highest and lowest, respectively, daily water levels generated by the EDEN surface-water model for that location. The highest ground elevation on the tree island is plotted and water levels above this elevation are considered overtopping elevations at the tree island.</p>
<p><em>Volin, J., Liu, Z., Higer, A., Mazzotti, F., Owen, D., Allen, J., and Pearlstine, L., 2008, <a href="http://digitalcommons.uconn.edu/nrme_articles/8/">Validation of a Spatially Continuous EDEN Water-Surface Model for the Everglades, Florida</a>, Department of Natural Resources Management and Engineering, University of Connecticut, 55 <abbr title="pages">p.</abbr></em></p>
<?php require ($_SERVER['DOCUMENT_ROOT'] . '/../eden/ssi/eden-foot.php'); ?>